name: robot_upstart_ci

on:
  push:
    branches: [foxy-devel]
  pull_request:
    branches: [foxy-devel]

jobs:
  jazzy_ci:
    name: Jazzy
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: jazzy
      - uses: ros-tooling/action-ros-ci@v0.3
        id: action_ros_ci_step
        with:
          target-ros2-distro: jazzy
          import-token: ${{ secrets.GITHUB_TOKEN }}
          skip-tests: false
          package-name:
            robot_upstart

  humble_ci:
    name: Humble
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: humble
      - uses: ros-tooling/action-ros-ci@v0.3
        id: action_ros_ci_step
        with:
          target-ros2-distro: humble
          import-token: ${{ secrets.GITHUB_TOKEN }}
          skip-tests: false
          package-name:
            robot_upstart